//! Test with a fresh signature generated by Go using current code

use goldilocks_crypto::{ScalarField, Point, verify_signature, sign, Fp5Element};
use hex;

#[test]
fn test_fresh_go_signature() {
    println!("\n=== Testing with Fresh Go Signature ===\n");
    
    // Generate a fresh signature using Rust (with fixed code)
    let private_key = ScalarField::from_bytes_le(&{
        let mut bytes = [0u8; 40];
        bytes[0] = 1; // sk = 1
        bytes
    }).unwrap();
    let private_key_bytes = private_key.to_bytes_le();
    
    let message = {
        let mut msg = [0u8; 40];
        for i in 0..40 {
            msg[i] = i as u8;
        }
        msg
    };
    
    // Sign with Rust (fresh signature with fixed code)
    let signature = sign(&private_key_bytes, &message).unwrap();
    
    // Compute public key
    let generator = Point::generator();
    let public_key_point = generator.mul(&private_key);
    let public_key_bytes = public_key_point.encode().to_bytes_le();
    
    println!("Fresh signature test:");
    println!("  Private key: {}...", hex::encode(&private_key_bytes[..8]));
    println!("  Public key: {}...", hex::encode(&public_key_bytes[..8]));
    println!("  Message: {}...", hex::encode(&message[..8]));
    println!("  Signature: {}...", hex::encode(&signature[..16]));
    
    // Verify the signature
    let is_valid = verify_signature(&signature, &message, &public_key_bytes).unwrap();
    
    println!("\nVerification result: {}", if is_valid { "✅ VALID" } else { "❌ INVALID" });
    
    if is_valid {
        println!("\n✅ Fresh signature verifies correctly!");
        println!("   The fix is working for fresh signatures!");
    } else {
        println!("\n❌ Fresh signature still fails verification");
        println!("   There's still a bug in the verification code");
        
        // Debug: Extract s and e
        let s = ScalarField::from_bytes_le(&signature[..40]).unwrap();
        let e = ScalarField::from_bytes_le(&signature[40..]).unwrap();
        
        // Reconstruct k
        let e_times_sk = e.mul(&private_key);
        let e_times_sk_canonical = e_times_sk.to_canonical();
        let k = s.add(e_times_sk_canonical);
        
        // Compute expected R
        let expected_r = generator.mul(&k);
        let expected_r_encoded = expected_r.encode();
        
        // Compute R using verification (current approach - no adjustment needed)
        let public_point = Point::decode(&Fp5Element::from_bytes_le(&public_key_bytes).unwrap()).unwrap();
        let computed_r = Point::mul_add2(&generator, &public_point, &s, &e);
        let computed_r_encoded = computed_r.encode();
        
        println!("\nDebug:");
        println!("  Expected R: {}...", hex::encode(&expected_r_encoded.to_bytes_le()[..16]));
        println!("  Computed R: {}...", hex::encode(&computed_r_encoded.to_bytes_le()[..16]));
        println!("  Match: {}", expected_r_encoded.0.iter().zip(computed_r_encoded.0.iter())
            .all(|(a, b)| a.0 == b.0));
    }
    
    assert!(is_valid, "Fresh signature should verify correctly");
}


