//! Stress Test for Auth Token Authentication
//!
//! This example sends 100s of requests using auth tokens generated by the Rust signer
//! to investigate invalid signature authentication issues.
//!
//! Usage:
//!   cargo run --example stress_test_auth --release
//!
//! Environment variables:
//!   API_PRIVATE_KEY - Your API private key (hex, with or without 0x prefix)
//!   API_KEY_INDEX   - API key index (default: 5)
//!   ACCOUNT_INDEX   - Account index (default: 361816)
//!   BASE_URL        - Base URL (default: https://mainnet.zklighter.elliot.ai)

use std::env;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use reqwest::Client;
use serde_json::Value;
use tokio::time::sleep;

use signer::KeyManager;

// Try to load .env file if available (optional)
fn load_dotenv() {
    // Try to load .env file manually from current directory or parent directories
    if let Ok(current_dir) = env::current_dir() {
        let env_files = [
            current_dir.join(".env"),
            current_dir.join("..").join(".env"),
            current_dir.join("..").join("..").join(".env"),
        ];
        for env_file in env_files.iter() {
            if env_file.exists() {
                if let Ok(content) = std::fs::read_to_string(env_file) {
                    for line in content.lines() {
                        let line = line.trim();
                        if line.is_empty() || line.starts_with('#') {
                            continue;
                        }
                        if let Some((key, value)) = line.split_once('=') {
                            let key = key.trim();
                            let value = value.trim().trim_matches('"').trim_matches('\'');
                            if env::var(key).is_err() {
                                env::set_var(key, value);
                            }
                        }
                    }
                    break;
                }
            }
        }
    }
}

/// Configuration loaded from environment variables
struct Config {
    api_private_key: String,
    api_key_index: u8,
    account_index: i64,
    base_url: String,
}

impl Config {
    fn from_env() -> Result<Self, String> {
        let api_private_key = env::var("API_PRIVATE_KEY")
            .map_err(|_| "API_PRIVATE_KEY environment variable is required")?;
        
        let api_key_index = env::var("API_KEY_INDEX")
            .unwrap_or_else(|_| "5".to_string())
            .parse::<u8>()
            .map_err(|_| "API_KEY_INDEX must be a valid u8")?;
        
        let account_index = env::var("ACCOUNT_INDEX")
            .unwrap_or_else(|_| "361816".to_string())
            .parse::<i64>()
            .map_err(|_| "ACCOUNT_INDEX must be a valid i64")?;
        
        let base_url = env::var("BASE_URL")
            .unwrap_or_else(|_| "https://mainnet.zklighter.elliot.ai".to_string());
        
        Ok(Config {
            api_private_key,
            api_key_index,
            account_index,
            base_url,
        })
    }
}

/// Statistics for tracking request results
struct Stats {
    total: u64,
    success: u64,
    auth_failures: u64,
    other_errors: u64,
    start_time: SystemTime,
}

impl Stats {
    fn new() -> Self {
        Self {
            total: 0,
            success: 0,
            auth_failures: 0,
            other_errors: 0,
            start_time: SystemTime::now(),
        }
    }
    
    fn record_success(&mut self) {
        self.total += 1;
        self.success += 1;
    }
    
    fn record_auth_failure(&mut self) {
        self.total += 1;
        self.auth_failures += 1;
    }
    
    fn record_error(&mut self) {
        self.total += 1;
        self.other_errors += 1;
    }
    
    fn print_summary(&self) {
        let elapsed = self.start_time.elapsed().unwrap_or(Duration::ZERO);
        let rate = if elapsed.as_secs() > 0 {
            self.total as f64 / elapsed.as_secs() as f64
        } else {
            0.0
        };
        
        println!("\n{}", "=".repeat(80));
        println!("STRESS TEST SUMMARY");
        println!("{}", "=".repeat(80));
        println!("Total Requests:     {}", self.total);
        println!("Successful:         {} ({:.2}%)", 
                 self.success, 
                 if self.total > 0 { (self.success as f64 / self.total as f64) * 100.0 } else { 0.0 });
        println!("Auth Failures:      {} ({:.2}%)", 
                 self.auth_failures,
                 if self.total > 0 { (self.auth_failures as f64 / self.total as f64) * 100.0 } else { 0.0 });
        println!("Other Errors:       {} ({:.2}%)", 
                 self.other_errors,
                 if self.total > 0 { (self.other_errors as f64 / self.total as f64) * 100.0 } else { 0.0 });
        println!("Elapsed Time:       {:.2}s", elapsed.as_secs_f64());
        println!("Request Rate:       {:.2} req/s", rate);
        println!("{}", "=".repeat(80));
    }
}

/// Make a single authenticated request
async fn make_authenticated_request(
    client: &Client,
    base_url: &str,
    endpoint: &str,
    auth_token: &str,
    params: &[(&str, &str)],
) -> Result<Value, String> {
    let url = format!("{}{}", base_url, endpoint);
    
    let mut request = client.get(&url);
    
    // Add auth token as Authorization header (preferred method)
    request = request.header("Authorization", auth_token);
    
    // Also add as query parameter (for compatibility)
    request = request.query(&[("auth", auth_token)]);
    
    // Add other query parameters
    for (key, value) in params {
        request = request.query(&[(key, value)]);
    }
    
    let response = request.send().await
        .map_err(|e| format!("Request failed: {}", e))?;
    
    let status = response.status();
    let text = response.text().await
        .map_err(|e| format!("Failed to read response: {}", e))?;
    
    if status.is_success() {
        let json: Value = serde_json::from_str(&text)
            .unwrap_or_else(|_| Value::String(text));
        Ok(json)
    } else if status == 401 {
        Err(format!("AUTH_FAILURE: {} - {}", status, text))
    } else {
        Err(format!("ERROR {}: {}", status, text))
    }
}

/// Test multiple endpoints
async fn test_endpoints(
    client: &Client,
    config: &Config,
    auth_token: &str,
    stats: &mut Stats,
) {
    // Test 1: Account Active Orders
    let result = make_authenticated_request(
        client,
        &config.base_url,
        "/api/v1/accountActiveOrders",
        auth_token,
        &[
            ("account_index", &config.account_index.to_string()),
            ("market_id", "0"),
        ],
    ).await;
    
    match result {
        Ok(_) => {
            stats.record_success();
            print!(".");
        }
        Err(e) => {
            if e.contains("AUTH_FAILURE") {
                stats.record_auth_failure();
                println!("\n❌ Auth failure: {}", e);
            } else {
                stats.record_error();
                print!("E");
            }
        }
    }
    
    // Test 2: Account Limits
    let result = make_authenticated_request(
        client,
        &config.base_url,
        "/api/v1/accountLimits",
        auth_token,
        &[
            ("account_index", &config.account_index.to_string()),
        ],
    ).await;
    
    match result {
        Ok(_) => {
            stats.record_success();
            print!(".");
        }
        Err(e) => {
            if e.contains("AUTH_FAILURE") {
                stats.record_auth_failure();
                println!("\n❌ Auth failure: {}", e);
            } else {
                stats.record_error();
                print!("E");
            }
        }
    }
    
    // Test 3: Account Metadata
    let result = make_authenticated_request(
        client,
        &config.base_url,
        "/api/v1/accountMetadata",
        auth_token,
        &[
            ("by", "index"),
            ("value", &config.account_index.to_string()),
        ],
    ).await;
    
    match result {
        Ok(_) => {
            stats.record_success();
            print!(".");
        }
        Err(e) => {
            if e.contains("AUTH_FAILURE") {
                stats.record_auth_failure();
                println!("\n❌ Auth failure: {}", e);
            } else {
                stats.record_error();
                print!("E");
            }
        }
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Try to load .env file if it exists
    load_dotenv();
    
    println!("🚀 Lighter Rust Auth Token Stress Test");
    println!("{}", "=".repeat(80));
    
    // Load configuration
    let config = Config::from_env()
        .map_err(|e| format!("Configuration error: {}", e))?;
    
    println!("\n📋 Configuration:");
    println!("  API Key Index:  {}", config.api_key_index);
    println!("  Account Index:  {}", config.account_index);
    println!("  Base URL:       {}", config.base_url);
    println!("  Private Key:    {}...", &config.api_private_key[..config.api_private_key.len().min(16)]);
    
    // Initialize key manager
    println!("\n🔑 Initializing key manager...");
    let key_manager = KeyManager::from_hex(&config.api_private_key)
        .map_err(|e| format!("Failed to initialize key manager: {}", e))?;
    
    // Generate auth token
    println!("🔐 Generating auth token...");
    let deadline = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs() as i64 + (7 * 3600); // 7 hours from now
    
    let auth_token = key_manager.create_auth_token(
        deadline,
        config.account_index,
        config.api_key_index,
    ).map_err(|e| format!("Failed to create auth token: {}", e))?;
    
    println!("✅ Auth token generated");
    println!("   Token: {}...", &auth_token[..auth_token.len().min(80)]);
    println!("   Deadline: {} ({} hours from now)", deadline, 7);
    
    // Create HTTP client
    let client = Client::builder()
        .timeout(Duration::from_secs(30))
        .build()
        .map_err(|e| format!("Failed to create HTTP client: {}", e))?;
    
    // Test the token once before stress testing
    println!("\n🧪 Testing auth token with single request...");
    let mut test_stats = Stats::new();
    test_endpoints(&client, &config, &auth_token, &mut test_stats).await;
    
    if test_stats.success > 0 {
        println!("\n✅ Initial test successful! Auth token is valid.");
    } else if test_stats.auth_failures > 0 {
        println!("\n❌ Initial test failed with auth errors!");
        println!("   This indicates the auth token signature is invalid.");
        println!("   Token: {}", auth_token);
        test_stats.print_summary();
        return Ok(());
    }
    
    // Stress test: Send 100s of requests
    println!("\n🔥 Starting stress test (100 requests)...");
    println!("   Each '.' = success, 'E' = error, '❌' = auth failure");
    
    let num_requests = 100;
    let mut stats = Stats::new();
    
    for i in 0..num_requests {
        test_endpoints(&client, &config, &auth_token, &mut stats).await;
        
        // Print progress every 10 requests
        if (i + 1) % 10 == 0 {
            println!("\n   Progress: {}/{} requests completed", i + 1, num_requests);
        }
        
        // Small delay to avoid rate limiting (10ms between requests)
        sleep(Duration::from_millis(10)).await;
    }
    
    // Print final summary
    stats.print_summary();
    
    if stats.auth_failures > 0 {
        println!("\n⚠️  WARNING: {} authentication failures detected!", stats.auth_failures);
        println!("   This indicates potential issues with:");
        println!("   1. Auth token generation (signature format)");
        println!("   2. Message hashing (Poseidon2)");
        println!("   3. Signature algorithm (Schnorr)");
        println!("\n   Debug information:");
        println!("   - Token: {}...", &auth_token[..auth_token.len().min(100)]);
        println!("   - API Key Index: {}", config.api_key_index);
        println!("   - Account Index: {}", config.account_index);
    } else if stats.success == stats.total {
        println!("\n✅ SUCCESS: All {} requests completed successfully!", stats.total);
        println!("   Auth token signature is valid and working correctly.");
    }
    
    Ok(())
}

